fix = true

[lint]
select = ["ALL"]
ignore = [
  "TRY003",  # raise-vanilla-args
]

[lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",  # Use of `assert` is required in pytest
  "PLR2004",  # Magic values are expected for test inputs and outputs
  "SLF001",  # Accessing private members is necessary for mocking and white-box testing
  "D",  # Test function names are descriptive enough; docstrings are redundant
]

[lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]

[lint.pydocstyle]
convention = "google"
